imports:
    - { resource: config.yml }

doctrine:
    orm:
        entity_managers:
            default:
                metadata_cache_driver:
                    cache_provider: pim
                result_cache_driver:
                    cache_provider: pim
                query_cache_driver:
                    cache_provider: pim
monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: warning
            handler:      nested
            channels: [!eventstore]
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: info
            channels: [!eventstore]
        console:
            type:  console
            channels: [!eventstore]
        event:
            type: stream
            path: '%kernel.logs_dir%/events.log'
            level: info
            channels: [eventstore]

oro_assetic:
    css_debug:      ~
    css_debug_all:  false

doctrine:
    orm:
        metadata_cache_driver: apcu
