parameters:
    pim_event_store.event_subscriber.store.class: Pim\Bundle\EventStoreBundle\StoreSubscriber

services:
    pim_event_store.event_subscriber.index_products:
        class: '%pim_event_store.event_subscriber.store.class%'
        arguments:
          - '@logger'
          - '@pim_user.context.user'
          - '@pim_catalog.normalizer.standard.product.product_value'
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: eventstore }
